### ISSUE TITLE
add fields for shipping vs billing address

### ISSUE THREAD

**Issue by abbi-gehl** [JohnnyG1234/Server-Side-Project#9]

**Comment by abbi-gehl** [comment]
We need a way for the user to specify a shipping vs billing address when placing an order

**Comment by JohnnyG1234** [comment]
I think this is fixed, might be some issues with the validation still though

**Comment by JohnnyG1234** [comment]
ok so there is still some cookie issues I'm working on but I think its good enough to close this issue
